#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'


sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
echo -e "Hello World!" > /var/www/html/index.html
echo -e "Hello World!" > /var/www/html/index.htm


sudo service nginx restart
